// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzF376y_pSdR3zj4g_JnRyu5dk6EpCsaI',
    appId: '1:246506530060:web:c692e1ac6373f1e8d71529',
    messagingSenderId: '246506530060',
    projectId: 'todo-list-flutter-a0f23',
    authDomain: 'todo-list-flutter-a0f23.firebaseapp.com',
    storageBucket: 'todo-list-flutter-a0f23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJDb8RoQbCVfxwwb2OlCVB9VJOw0qpUrU',
    appId: '1:246506530060:android:bc61ec6126cf0f28d71529',
    messagingSenderId: '246506530060',
    projectId: 'todo-list-flutter-a0f23',
    storageBucket: 'todo-list-flutter-a0f23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtkNPspVqkfFz0EyvJ4QIuySAftzkUtIc',
    appId: '1:246506530060:ios:278425cc72938768d71529',
    messagingSenderId: '246506530060',
    projectId: 'todo-list-flutter-a0f23',
    storageBucket: 'todo-list-flutter-a0f23.appspot.com',
    iosClientId: '246506530060-q7ip9hl3s432sgrhf3espjn86ffs7kr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoListFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtkNPspVqkfFz0EyvJ4QIuySAftzkUtIc',
    appId: '1:246506530060:ios:278425cc72938768d71529',
    messagingSenderId: '246506530060',
    projectId: 'todo-list-flutter-a0f23',
    storageBucket: 'todo-list-flutter-a0f23.appspot.com',
    iosClientId: '246506530060-q7ip9hl3s432sgrhf3espjn86ffs7kr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoListFlutter',
  );
}
